### ISSUE TITLE
Some level descriptions include French texts

### ISSUE THREAD

**Issue by Wuzzy2** [Neverball/neverball#115]
In Neverball 1.6.0, there are many levels which contain French texts in their original description, especially in the level sets Tour de force and Retour de force.
I think this is a bad idea, the source texts should be English-only, everything else just messes up the translation. Neverball has a French translation anyways.

I propose to either translate the French portions to English or to remove them.

**Comment by parasti** [comment]
There used to be a long explanation for why it is the way it is, but the short version is that translators should copy the source string and translate the portions in English, leaving the rest intact.

**Comment by Wuzzy2** [comment]
So the French texts are inserted here intentionally, even if the source language clearly is English? This sounds weird.
I am excited to hear the circumstances that lead to such a strange decision. I doubt they will convince me that it is really better to insert random French portions into the source strings.

From a player standpoint, it is just irritating.

**Comment by ChallengeSY** [comment]
From what I remember in the document, those 50+ levels with French text were designed prior to the implementation of the localization feature that was added in release 1.5.0.

**Comment by fwp** [comment]
> So the French texts are inserted here intentionally, even if the source language clearly is English?

Yes, the author of the level sets _Tour de force_ and _Retour de force_ intentionally included them for added flair. You will have noticed that the names of those two level sets are themselves in French.

There was a bit of discussion and background information about this in the Neverforum, but I wasn't able to find it through the Wayback Machine just now. Either way, I don't think that there is or should be a mandate banning every bit of content that's not in the primary language.

**Comment by Wuzzy2** [comment]
So the justifications you gave me so far are “because the author wanted it so” and “for added flair” and “the texts were written before internationalization”. Not really convincing. The last one is more a reason to translate or remove those parts. I also don't think those French bits add any flair to the levels, I think they are just plain irritating. Is there really nobody else who is irritated by those French bits?

I still think it is pointless as it is confusing. I don't speak French. If I want French, I just set the game's language to French. Why mixing two languages?
Would you also mix English and Chinese if the original author dictates so?
I am not against banning French, there is an entire translation ready. I am just against mixing two languages for no good reason.

Note I am okay with the names, names are different.

**Comment by parasti** [comment]
You are, in fact, the first person to find them irritating and say so. They've been there for 12-13 years.

Since I didn't really add any context, I have to correct myself now. Mehdi, the designer of those level sets, was and remains one of the most influential people who have ever worked on Neverball. But that really has nothing to with why the French portions are staying. If anyone else were to use the same approach in their levels for their native language, I would not feel any differently. It adds personality and a sense of a worldwide community. Most people don't find them irritating. It's at most an extra key press or two on the part of the translator.

And that's that. Regardless, thanks for your input, it's always appreciated.

**Comment by rlk** [comment]
I see this issue is closed, but I thought I might comment anyway, since the decision was mine way back in 2003. Ultimately, as it has been stated, MYM is a native speaker of French, and was the first person ever to contribute a level to Neverball. I kept his French level descriptions because I appreciated the international feel, which I wanted from a truly open Open Source project.

That said, however, the precedent was set by one of my levels. I had written an early version of the curve generator tool and made a level featuring a large winding cylinder. I gave it the description "Ceci n'est pas une pipe" which is a reference to the artist Magritte. Translating that into any language other than French would spoil the reference.
