### ISSUE TITLE
Wooden walls of Bonus Level III, Neverball Hard can block view

### ISSUE THREAD

**Issue by Wuzzy2** [Neverball/neverball#117]
In Neverball 1.6.0, in the Bonus Level III of Neverball Hard, your camera can sometimes be in an unfortunate angle so that it is behind one of the wooden walls so the view to your ball is blocked.

Can be easily reproduced, just start the level, activate manual camera, press the right mouse button to rotate the camera by 90°, then move towards the edge so the wooden wall becomes visible. Now your ball is hidden because of the wall. The issue seems to be with most walls in this level.

Interestingly, in this level the ceiling *will* become semi-transparent if the camera is behind it.
I noticed that in many levels, walls normally become semi-transparent (which is a very good idea, good job!). But not in this level for the wooden walls.

**Comment by fwp** [comment]
There's no way to change the texture of a surface depending on the position of the camera. If a wall is to appear transparent, it will need to be transparent all the time.

This means that when you get inside the corridor next to the starting corridor, that wall would now be transparent instead of wooden. And of course the blocked-view problem is the same on both sides so the other side of the wall, the one facing the starting corridor, would have to be transparent, too. In the end, the entire level would be full of transparent walls, which clearly runs counter to the intended design.

These small visibility issues pop up here and there in Neverball, and I think the general view is that they're not much of a problem. Levels, at least the official ones, are usually designed in a way that minimizes such occurrences.

So I'm closing this as wontfix (more like cantreallyfix).
