### ISSUE TITLE
Neverball C++ and CMake support

### ISSUE THREAD

**Issue by acterhd** [Neverball/neverball#136]
Hello. When Neverball will: 
- Support CMake and Visual Studio?
- Support C++11?
I can't rework C version. Sorry, I working only with C++.

**Comment by rlk** [comment]
There is no intention to port the Neverball source to C++, or the Neverball build system to CMake or Visual Studio.

The standard cross-platform approach to open source development in C has served the project well since its inception more than 13 years ago. There is no advantage to switching languages or build systems, and such sweeping changes are likely to introduce new bugs and maintenance challenges. Thus there is no reason to change and every reason to remain on course.

**Comment by acterhd** [comment]
Problem with NVidia OptiX or other ray tracers. They may writed in C++, and
not compatible with C. Also, "Makefile" also causes problems with
compilation under Windows or execution. When I tried to compile in Windows
10 with Linux Bash, I had problem with OpenGL version. X Server from 3rd
developers uses same OpenGL, as WebGL 1.0.

**Comment by ChallengeSY** [comment]
On the other hand, I had no problems getting a remotely working build compiling natively under Windows, but without native language support or PhysicsFS. I have since accidentally broken my MinGW64 installation, and I have no idea how to reset it.
