### ISSUE TITLE
Track2.ogg contains annoying high pitched noise

### ISSUE THREAD

**Issue by R33D3M33R** [Neverball/neverball#137]
Listening to track2.ogg is very painful as it contains an annoying high pitched noise. Please consider remixing the track or replacing it with a new one. Thanks!

**Comment by tonesfrommars** [comment]
Thanks for your input. Unfortunately, remixing the original audio track isn't a realistic proposition, since they were created on an analog synthesizer more than a decade ago. Experiencing the sound in question as painful and annoying is subjective and dependent on the user's listening environment. Personally, I have never had problems with it. I couldn't justify replacing this original track with a new one unless it was clear that it was a significant issue for a substantial swath of users, particularly because it's one of the originals.

**Comment by crazyBaboon** [comment]
Interesting. I do detect a peak at around 10kHz (using Audacity) in track2.ogg that does not seem to exist on other tracks. Now I think this is due to a musical squeak  but I am not sure. It does not annoy me in any way. But again, that is maybie because of my age... younger people in their 10s or 20s tend to be more sensitive to high frequencies, so they might get bothered. And as tonesfrommars said, it will ultimately depend you your speaker setup. I do like the track and it would be a shame to remix/filter a premium original piece of work, but if enough (young) people do honestly complain about it, the devs naturally should look for a solution...

**Comment by R33D3M33R** [comment]
Yes, it really does depend on the speakers. I have tested it with in ear headphones and the noise is not noticeable.

**Comment by parasti** [comment]
An easy solution to this is turning down the game volume. The volume slider for background music is in the options menu.

**Comment by qwertychouskie** [comment]
It might make sense to just run it through a filter that removes high frequencies.

**Comment by tonesfrommars** [comment]
Closing this, objectively it is a non-issue. Altering the original audio would require a strong consensus to the contrary.
