### ISSUE TITLE
Specular exponent handling seems broken

### ISSUE THREAD

**Issue by fwp** [Neverball/neverball#161]
In **mtrl.c::load_mtrl**, _base->h[0]_ is converted to a _GLubyte_ using **mtrl.h::tobyte**. However, that macro was made for float values between 0.0 and 1.0 that are then multiplied by 255.0, while the specular exponent is in the [0.0..128.0] range. As a result, the value that gets stored in _mp->h_ and is later used in comparisons may not be the one that was intended.

**Comment by parasti** [comment]
Hey, nice catch. How did you find it? I've definitely encountered instances where values above 1.0 don't seem to make a difference, but that was a while ago; couldn't really find any cases where fixing this made a noticeable difference in the game. The vast majority of materials don't have any specularity, so there would have been very few opportunities where this issue could have popped up. Specifically, it would only become evident when two materials with specularity are rendered one after the other while having different specular exponents.

In any case, the point is now fixed: 56efa2c5

**Comment by parasti** [comment]
Dove into this a bit and found that it probably has never actually caused any rendering bugs in the game. Since the only purpose of that cache value is to test for difference, the "wrong" value is actually sufficient - it is wrong, but still different. It has edge cases, but you would have to go out of your way to encounter them. For example, in the old code, 0.5 is considered "equal" to 1.505, but you would be inclined to use the (likely visually indistinguishable) 1.5, which is _not_ considered equal.

```
(gdb) p (unsigned char) (0.5 * 255.0)
$16 = 127 '\177'
(gdb) p (unsigned char) (1.505 * 255.0)
$17 = 127 '\177'
(gdb) p (unsigned char) (1.5 * 255.0)
$22 = 126 '~'
(gdb) p (unsigned char) (1.0 * 255.0)
$18 = 255 '\377'
(gdb) p (unsigned char) (2.005 * 255.0)
$19 = 255 '\377'
```

**Comment by fwp** [comment]
> Hey, nice catch. How did you find it?

I was combing through some code to check for possible rendering differences between Neverball and Nuncabola. Came across _tobyte_ and wondered how it would (or should) behave when given values outside [0.0, 1.0]. mapc doesn't restrict the diffuse/ambient/specular/emissive values, and, interestingly, the OpenGL spec also states that they're not clamped. I'm not sure, however, what a red component of 2.0 or something similar would accomplish.

As an experiment, I inserted a call into Nuncabola's version of _tobyte_ that clamped _f_ to [0.0, 1.0] before multiplying it with 255.0. Eventually, I realized that now all nonzero shininess values would end up as 255, which is clearly undesirable. A quick test also showed that the kind of specularity changes that you mentioned actually do happen. The funny thing is that I both knew about the range of the specular exponent and the range expected by _tobyte_, yet I never made the connection.

I have to ask, though, since both _base->h[0]_ and _mp->h_ are four bytes long, why perform any conversion at all?

> Dove into this a bit and found that it probably has never actually caused any rendering bugs in the game.

Yeah, it was more of a conceptual issue, otherwise we would probably have noticed it much earlier.

**Comment by parasti** [comment]
> I have to ask, though, since both base->h[0] and mp->h are four bytes long, why perform any conversion at all?

It has to do with GL state change minimization. Storage size doesn't really matter here. This conversion gets us two things:

1. It side-steps the issue of testing floating-point values for equality. Since FP computations can be affected by processor architecture, compiler flags, standard library and the phase of the moon, it's generally better not to test for equality down to the last bit, because you may end up in a situation where two values from the same source don't compare equal. That's an extra state change where none was needed.
2. It reduces a normalized floating-point value down to 255 integer values, so if you were to use every shade of red available to you, you would still get no more than 255 state changes.

It may sound like a crucial performance benefit, given the above, but in the case of specular exponent, the conversion is mostly there just for code completeness. You could try testing the floating-point value directly, and you probably wouldn't notice a difference performance-wise.

**Comment by fwp** [comment]
> It has to do with GL state change minimization. Storage size doesn't really matter here.

I wasn't sure whether the focus was more on the coalescing of very similar float values or the quick comparisons (one integer vs. four floats per material property). Your explanation clears that up.

> [...] and the phase of the moon

I can confirm this. Tests show that material shininess is +0.0 at full moon, -0.0 at new moon, and some other value once in a blue moon.
