### ISSUE TITLE
New game mode request: Just move the ball instead of tilting the floor.

### ISSUE THREAD

**Issue by stavrossk** [Neverball/neverball#167]
I know that this would be possibly require good amount of work, but I think that it would be beneficial to the game's popularity long-term. So my idea is to add a game mode where instead of tilting the floor to move the ball, you directly move the ball with the arrow keys without tilting the floor at all. Because as it is, the gameplay is very difficult and confusing for me. I constantly lose control of the ball and it always hits the walls bouncing in the opposite direction way too much. Thoughts?

**Comment by ChallengeSY** [comment]
I have no idea how feasible it is to implement the alternative control mechanism...

Still, one of the common beginner mistakes is consistently tilting the fields all the way. While this is not a big deal throughout the first half of Neverball Easy, once you reach level 10, you will encounter the first segment where not all of the level is walled.

... and if you skip to any other official level set, then none of their first levels are entirely walled. In fact, many of those levels have no walls at all to protect against fall outs.

**Comment by parasti** [comment]
I can understand the frustration, but would have to say no to the idea. My personal belief is that games are best when they're focused, and I think the controls are (and should remain) the focus of Neverball. 

I think the biggest hurdle in learning Neverball controls is the walled early levels. Falling out should be taught early and taught often. The "safety" of walls is really an illusion, because walls in Neverball don't work like that. They throw you off course and confuse you. They're a dangerous obstacle to be navigated/used carefully. That said, fixing it would require a large restructuring/reworking of the level sets, which is no small undertaking.

Going off on a tangent here...

Unlocking Neverball levels one by one remains among my most memorable gaming experiences of all time. I attribute that in large part to the controls. Yet, as much as I struggled with it, it's a skill that is never lost once learned, just like riding a bicycle. Those same levels are easy now, despite the fact that I don't even play Neverball on any sort of regular basis any more.

It's important to point out that back then there was a much bigger competitive/community aspect to the game, that made it very fun to keep going. I was submitting replays to a replay contest before I had unlocked all the levels. I really wish that could be brought back.

**Comment by rlk** [comment]
Indeed, that would not be Neverball. The physics is the essence of it.

**Comment by stavrossk** [comment]
Ok, cool I understand. What about adding an alternative top-down view camera? My main source of frustration is the camera.

**Comment by ChallengeSY** [comment]
Closest we have to camera settings is a series of config options as documented by **doc/manual.txt**. I have no experience with the camera settings, but there is a pre-1.2.6 set documented that will provide a more zoomed out perspective.

**Comment by qwertychouskie** [comment]
Also, do you play with the keyboard or mouse?  I personally recommend the keyboard as it is virtually impossible to have a perfectly level floor with the mouse.  Also make the game fullscreen and at your monitor's native resolution.

**Comment by stavrossk** [comment]
> Also, do you play with the keyboard or mouse? I personally recommend the keyboard as it is virtually impossible to have a perfectly level floor with the mouse. Also make the game fullscreen and at your monitor's native resolution.

@qwertychouskie  I play with the keyboard and it's much easier and convenient than playing with the mouse I might say, but my issue is not with the input method itself but with the tilting of the floor.

The tilting kinda confuses me big-time but I guess I'll have to give it another try since I like this game so much and see where that goes.

Thanks again everyone for your suggestions.
(and sorry for the late reply, I just saw the notification).
